name = "boringjobs"
version = "<%= package.version %>"
description = "Simple project to verify the functionality of cannon"
keywords = ["boring", "jobs", "cannon"]

[setting.msg]
defaultValue = "Boring Jobs"
description="The greeting passed to the constructor"

[contract.boringjobs]
artifact = "BoringJobs"
args = ["<%= settings.msg %>"]
